export const logoMap: Record<string, string> = {
  pppoker: '/image.webp',
  xpoker: '/xpoker_logo.webp',
  clubgg: '/clubGG_logo.webp',
  phd_logo_new: '/PDH_logo_no_background.webp',
  nuts_poker_logo: '/nuts_poker_logo.webp',
  pokerbros_logo: '/pokerbros_logo.webp',
  coinpoker_logo: '/coinpoker_logo.webp',
};

export const renderStars = (rating: number) =>
  '★'.repeat(rating) + '☆'.repeat(5 - rating);


export const badgeLabels = {
  ru: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asia',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Centralized',
    soft: '🐟 Soft game',
    highRakeback: '💰 High Rakeback',
    verified: '✅ Verified',
    allLimits: '📊 All Limits',
    nonStop: '⏱ NonStop',
    international: '🌍 International',
    australia: '🇦🇺 Australia',
  },
  en: { 
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asia',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Centralized',
    soft: '🐟 Soft game',
    highRakeback: '💰 High Rakeback',
    verified: '✅ Verified',
    allLimits: '📊 All Limits',
    nonStop: '⏱ NonStop',
    international: '🌍 International',
    australia: '🇦🇺 Australia',
   },
  es: {
    blockchain: "🔗 RNG en blockchain",
    usaPlayers: '🇺🇸 Jugadores USA',
    asia: '🏮 Asia',  
    topDeal: '💎 Oferta top',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 Club PDH',
    pdhPartner: '🤝 Socio PDH',
    centralized: '🏬 Centralizado',
    soft: '🐟 Juego suave',
    highRakeback: '💰 Alto rakeback',
    verified: '✅ Verificado',
    allLimits: '📊 Todos los límites',
    nonStop: '⏱ 24/7',
    international: '🌍 Internacional',
    australia: '🇦🇺 Australia',
   },
  uz: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 AQSh o‘yinchilari',
    asia: '🏮 Osiyo',
    topDeal: '💎 Top bitim',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH klubi',
    pdhPartner: '🤝 PDH hamkori',
    centralized: '🏬 Markazlashgan',
    soft: '🐟 Yengil o‘yin',
    highRakeback: '💰 Yuqori rakebek',
    verified: '✅ Tasdiqlangan',
    allLimits: '📊 Barcha limitlar',
    nonStop: '⏱ 24/7',
    international: '🌍 Xalqaro',
    australia: '🇦🇺 Avstraliya',
   },
  uk: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Азія',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Централізований',
    soft: '🐟 М’яка гра',
    highRakeback: '💰 Високий рейкбек',
    verified: '✅ Перевірено',
    allLimits: '📊 Усі ліміти',
    nonStop: '⏱ 24/7',
    international: '🌍 Міжнародний',
    australia: '🇦🇺 Australia',
   },
  it: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asia',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Centralizzato',
    soft: '🐟 Gioco soft',
    highRakeback: '💰 Rakeback alto',
    verified: '✅ Verificato',
    allLimits: '📊 Tutti i limiti',
    nonStop: '⏱ 24/7',
    international: '🌍 Internazionale',
    australia: '🇦🇺 Australia',
   },
  de: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asien',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Zentralisiert',
    soft: '🐟 Soft Game',
    highRakeback: '💰 Hoher Rakeback',
    verified: '✅ Verifiziert',
    allLimits: '📊 Alle Limits',
    nonStop: '⏱ 24/7',
    international: '🌍 International',
    australia: '🇦🇺 Australia',
   },
  pt: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Ásia',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Centralizado',
    soft: '🐟 Jogo soft',
    highRakeback: '💰 Rakeback alto',
    verified: '✅ Verificado',
    allLimits: '📊 Todos os limites',
    nonStop: '⏱ 24/7',
    international: '🌍 Internacional',
    australia: '🇦🇺 Australia',
   },
  fr: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asie',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Centralisé',
    soft: '🐟 Jeu soft',
    highRakeback: '💰 Rakeback élevé',
    verified: '✅ Vérifié',
    allLimits: '📊 Toutes les limites',
    nonStop: '⏱ 24/7',
    international: '🌍 International',
    australia: '🇦🇺 Australia',
   },
  tr: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asya',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Merkezi',
    soft: '🐟 Yumuşak oyun',
    highRakeback: '💰 Yüksek Rakeback',
    verified: '✅ Doğrulanmış',
    allLimits: '📊 Tüm limitler',
    nonStop: '⏱ 7/24',
    international: '🌍 Uluslararası',
    australia: '🇦🇺 Australia',
   },
  he: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 אסיה',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 ריכוזי',
    soft: '🐟 משחק רך',
    highRakeback: '💰 רייקבק גבוה',
    verified: '✅ מאומת',
    allLimits: '📊 כל הלימיטים',
    nonStop: '⏱ 24/7',
    international: '🌍 בינלאומי',
    australia: '🇦🇺 Australia',
   },
  ar: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 آسيا',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 مركزي',
    soft: '🐟 لعبة سهلة',
    highRakeback: '💰 رايك باك مرتفع',
    verified: '✅ موثّق',
    allLimits: '📊 جميع الحدود',
    nonStop: '⏱ 24/7',
    international: '🌍 دولي',
    australia: '🇦🇺 Australia',
   },
  id: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asia',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Tersentralisasi',
    soft: '🐟 Permainan mudah',
    highRakeback: '💰 Rakeback tinggi',
    verified: '✅ Terverifikasi',
    allLimits: '📊 Semua limit',
    nonStop: '⏱ 24/7',
    international: '🌍 Internasional',
    australia: '🇦🇺 Australia',
   },
  vi: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Châu Á',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Tập trung',
    soft: '🐟 Game dễ',
    highRakeback: '💰 Rakeback cao',
    verified: '✅ Đã xác minh',
    allLimits: '📊 Mọi mức cược',
    nonStop: '⏱ 24/7',
    international: '🌍 Quốc tế',
    australia: '🇦🇺 Australia',
   },
  fil: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 Asya',
    topDeal: '💎 Top Deal!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 Sentralisado',
    soft: '🐟 Madaling laro',
    highRakeback: '💰 Mataas na rakeback',
    verified: '✅ Na-verify',
    allLimits: '📊 Lahat ng limit',
    nonStop: '⏱ 24/7',
    international: '🌍 Internasyonal',
    australia: '🇦🇺 Australia',
   },
  th: {
    blockchain: "🔗 Blockchain RNG",
    usaPlayers: '🇺🇸 USA players',
    asia: '🏮 เอเชีย',
    topDeal: '💎 ดีลเด็ด!',
    playersChoice: '👍 Players’ Choice',
    cisPlayers: '🌐 CIS players',
    pdhClub: '🔥 PDH club',
    pdhPartner: '🤝 PDH partner',
    centralized: '🏬 แบบรวมศูนย์',
    soft: '🐟 เกมง่าย',
    highRakeback: '💰 เรคแบ็กสูง',
    verified: '✅ ตรวจสอบแล้ว',
    allLimits: '📊 ทุกลิมิต',
    nonStop: '⏱ 24/7',
    international: '🌍 นานาชาติ',
    australia: '🇦🇺 Australia',
   },
};

export const tooltips = {
  ru: {
    featured:
      'Клуб под управлением PokerDealsHub. Это гарантирует прозрачность, надёжность и сервис премиум-класса 24/7.',
  },
  en: {
    featured:
      'Club managed by PokerDealsHub. This ensures transparency, reliability, and premium-class service 24/7.',
  },
  es: {
    featured:
      'Club gestionado por PokerDealsHub. Esto garantiza transparencia, fiabilidad y un servicio de primera clase las 24 horas.',
  },
  uz: {
    featured:
      'PDH tomonidan boshqariladigan klub. Bu shaffoflik, ishonchlilik va 24/7 premium xizmatni kafolatlaydi.',
  },
  uk: {
    featured:
      'Клуб під управлінням PokerDealsHub. Це гарантує прозорість, надійність і сервіс преміумкласу 24/7.',
  },
  it: {
    featured:
      'Club gestito da PokerDealsHub. Questo garantisce trasparenza, affidabilità e un servizio premium 24/7.',
  },
  de: {
    featured:
      'Club unter der Leitung von PokerDealsHub. Das garantiert Transparenz, Zuverlässigkeit und erstklassigen Premium-Service rund um die Uhr.',
  },
  pt: {
    featured:
      'Clube gerenciado pela PokerDealsHub. Isso garante transparência, confiabilidade e um serviço premium 24/7.',
  },
  fr: {
    featured:
      'Club géré par PokerDealsHub. Cela garantit transparence, fiabilité et un service haut de gamme 24/7.',
  },
  tr: {
    featured:
      'PokerDealsHub tarafından yönetilen kulüp. Bu, şeffaflık, güvenilirlik ve 7/24 premium sınıf hizmet sağlar.',
  },
  he: {
    featured:
      'מועדון המנוהל על ידי PokerDealsHub. זה מבטיח שקיפות, אמינות ושירות ברמת פרימיום 24/7.',
  },
  ar: {
    featured:
      'نادٍ تديره PokerDealsHub. هذا يضمن الشفافية والموثوقية وخدمة من الدرجة الأولى على مدار الساعة طوال أيام الأسبوع.',
  },
  id: {
    featured:
      'Klub yang dikelola oleh PokerDealsHub. Ini menjamin transparansi, keandalan, dan layanan kelas premium 24/7.',
  },
  vi: {
    featured:
      'Câu lạc bộ do PokerDealsHub quản lý. Điều này đảm bảo sự minh bạch, độ tin cậy và dịch vụ hạng cao cấp 24/7.',
  },
  fil: {
    featured:
      'Club na pinamamahalaan ng PokerDealsHub. Tinitiyak nito ang transparency, reliability, at premium-class na serbisyo 24/7.',
  },
  th: {
    featured:
      'คลับที่บริหารโดย PokerDealsHub ซึ่งรับประกันความโปร่งใส ความน่าเชื่อถือ และบริการระดับพรีเมียมตลอด 24 ชั่วโมงทุกวัน',
  },
};

export const labl = {
  ru: {
    club: 'Клуб:',
    union: 'Союз:',
    geog: 'География:',
    platform: 'Платформа:',
    upTo: 'Рейкбэк до',
    bonusL: "Бонус:",
    getDeal: 'Получить сделку',
    rateBy: 'Рейтинг по дисциплинам',
    verif: 'Все предложения проходят внутреннюю проверку PDH. Мы гарантируем честные условия сотрудничества и клиентскую поддержку высшего класса в любое время суток.',
    readyJoin: 'Есть вопросы? Готовы вступить в клуб?',
    weAreHere: `Все сделки предоставляются бесплатно. Членство в клубах без KYC (не нужно отправлять документы).`,
    weAreHereNoKyc: `Узнайте о дополнительных преимуществах для вас и получите ссылку для регистрации.`,
    weAreHere2: `Пишите менеджеру PDH, работаем 24/7`,
    tgContact: 'Написать в Telegram',
    discordContact: 'Перейти в Discord',
  },
  en: {
    club: 'Club:',
    union: 'Union:',
    geog: 'Geography:',
    platform: 'Platform:',
    upTo: 'Rakeback up to',
    bonusL: "Bonus:",
    getDeal: 'Get the deal',
    rateBy: 'Game type ratings',
    verif: 'All offers undergo internal verification by PDH. We guarantee fair cooperation terms and top-class customer support available around the clock.',
    readyJoin: 'Got questions? Ready to join the club?',
    weAreHere: 'All deals are provided free of charge. Club membership is KYC-free (no documents required).',
    weAreHereNoKyc: `Learn about your additional benefits and get your registration link.`,
    weAreHere2: 'Message a PDH manager — we’re online 24/7.',
    tgContact: 'Message on Telegram',
    discordContact: 'Join our Discord',
  },
  es: {
    club: 'Club:',
    union: 'Unión:',
    geog: 'Geografía:',
    platform: 'Plataforma:',
    upTo: 'Rakeback hasta',
    bonusL: "Bono:",
    getDeal: 'Obtener esta oferta',
    rateBy: 'Calificación por disciplinas',
    verif: 'Todas las ofertas pasan una verificación interna de PDH. Garantizamos condiciones de cooperación justas y atención al cliente de primera clase disponible las 24 horas del día.',
    readyJoin: '¿Tiene preguntas? ¿Listo para unirse al club?',
    weAreHereNoKyc: `Conoce tus beneficios adicionales y obtén tu enlace de registro.`,
    weAreHere: 'Todas las ofertas se proporcionan de forma gratuita. La membresía en los clubes no requiere KYC (no es necesario enviar documentos).',
    weAreHere2: 'Escriba al gerente de PDH, trabajamos 24/7',
    tgContact: 'Contactar en Telegram',
    discordContact: 'Únete a Discord',
  },
  uz: {
    club: 'Klub:',
    union: 'Ittifoq:',
    geog: 'Geografiya:',
    platform: 'Platforma:',
    upTo: 'Rakebekgacha',
    bonusL: "Bonus:",
    getDeal: 'Bitimni olish',
    rateBy: 'Intizomlar reytingi',
    verif: 'Barcha takliflar PDH tomonidan ichki tekshiruvdan o‘tadi. Adolatli shartlar va 24/7 qo‘llab-quvvatlashni kafolatlaymiz.',
    readyJoin: 'Savollar bormi? Klubga qo‘shilishga tayyormisiz?',
    weAreHere: 'Barcha bitimlar bepul. Klubga a’zolik KYC talab qilmaydi (hujjatlar kerak emas).',
    weAreHereNoKyc: `Qo‘shimcha imtiyozlar va ro‘yxatdan o‘tish havolasini oling.`,
    weAreHere2: `PDH menejeriga yozing — 24/7 onlaynmiz.`,
    tgContact: 'Telegramda yozish',
    discordContact: 'Discordga qoʻshiling',
  },
  uk: {
    club: 'Клуб:',
    union: 'Союз:',
    geog: 'Географія:',
    platform: 'Платформа:',
    upTo: 'Рейкбек до',
    bonusL: "Бонус:",
    getDeal: 'Отримати сделку',
    rateBy: 'Рейтинг за дисциплінами',
    verif: 'Усі пропозиції проходять внутрішню перевірку PDH. Ми гарантуємо чесні умови співпраці та клієнтську підтримку найвищого класу цілодобово.',
    readyJoin: 'Є запитання? Готові вступити до клубу?',
    weAreHere: 'Усі сделки надаються безкоштовно. Членство в клубах без KYC (не потрібно надсилати документи).',
    weAreHereNoKyc: `Дізнайтеся про додаткові переваги для вас і отримайте посилання для реєстрації.`,
    weAreHere2: 'Напишіть менеджеру PDH — ми онлайн 24/7.',
    tgContact: 'Написати в Telegram',
    discordContact: 'Приєднатися до Discord',
  },
  it: {
    club: 'Club:',
    union: 'Union:',
    geog: 'Geografia:',
    platform: 'Piattaforma:',
    upTo: 'Rakeback fino al',
    bonusL: "Bonus:",
    getDeal: 'Ottieni il deal',
    rateBy: 'Valutazioni per disciplina',
    verif: 'Tutte le offerte vengono verificate internamente da PDH. Garantiamo condizioni di collaborazione corrette e un’assistenza clienti di prima classe disponibile 24 ore su 24.',
    readyJoin: 'Hai domande? Pronto a entrare nel club?',
    weAreHere: 'Tutti i deal sono offerti gratuitamente. L’iscrizione ai club è senza KYC (nessun documento richiesto).',
    weAreHereNoKyc: `Scopri i tuoi vantaggi aggiuntivi e ottieni il tuo link di registrazione.`,
    weAreHere2: 'Scrivi a un manager PDH — siamo online 24/7.',
    tgContact: 'Scrivi su Telegram',
    discordContact: 'Unisciti a Discord',
  },
  de: {
    club: 'Club:',
    union: 'Union:',
    geog: 'Geografie:',
    platform: 'Plattform:',
    upTo: 'Rakeback bis zu',
    bonusL: "Bonus:",
    getDeal: 'Deal sichern',
    rateBy: 'Bewertungen nach Disziplin',
    verif: 'Alle Angebote durchlaufen eine interne Prüfung durch PDH. Wir garantieren faire Kooperationsbedingungen und erstklassigen Kundensupport rund um die Uhr.',
    readyJoin: 'Noch Fragen? Bereit, dem Club beizutreten?',
    weAreHere: 'Alle Deals sind kostenlos. Die Club-Mitgliedschaft ist KYC-frei (keine Dokumente erforderlich).',
    weAreHereNoKyc: `Erfahre mehr über deine zusätzlichen Vorteile und erhalte deinen Registrierungslink.`,
    weAreHere2: 'Schreibe einem PDH-Manager — wir sind rund um die Uhr online.',
    tgContact: 'Auf Telegram schreiben',
    discordContact: 'Discord beitreten',
  },
  pt: {
    club: 'Clube:',
    union: 'União:',
    geog: 'Geografia:',
    platform: 'Plataforma:',
    upTo: 'Rakeback de até',
    bonusL: "Bônus:",
    getDeal: 'Obter esta oferta',
    rateBy: 'Avaliações por modalidade',
    verif: 'Todas as ofertas passam por uma verificação interna da PDH. Garantimos condições de cooperação justas e suporte ao cliente de primeira classe disponível 24 horas por dia.',
    readyJoin: 'Tem dúvidas? Pronto para entrar no clube?',
    weAreHere: 'Todas as ofertas são fornecidas gratuitamente. A adesão aos clubes é sem KYC (não é necessário enviar documentos).',
    weAreHereNoKyc: `Conheça seus benefícios adicionais e receba seu link de registro.`,
    weAreHere2: 'Fale com um gerente da PDH — estamos online 24/7.',
    tgContact: 'Falar no Telegram',
    discordContact: 'Entrar no Discord',
  },
  fr: {
    club: 'Club :',
    union: 'Union :',
    geog: 'Géographie :',
    platform: 'Plateforme :',
    upTo: 'Rakeback jusqu’à',
    bonusL: "Bonus :",
    getDeal: 'Obtenir l’offre',
    rateBy: 'Évaluations par discipline',
    verif: 'Toutes les offres font l’objet d’une vérification interne par PDH. Nous garantissons des conditions de coopération équitables et un support client de premier ordre disponible 24h/24.',
    readyJoin: 'Des questions ? Prêt à rejoindre le club ?',
    weAreHere: 'Toutes les offres sont fournies gratuitement. L’adhésion aux clubs est sans KYC (aucun document requis).',
    weAreHereNoKyc: `Découvrez vos avantages supplémentaires et obtenez votre lien d’inscription.`,
    weAreHere2: 'Écrivez à un manager PDH — nous sommes en ligne 24/7.',
    tgContact: 'Écrire sur Telegram',
    discordContact: 'Rejoindre Discord',
  },
  tr: {
    club: 'Kulüp:',
    union: 'Birlik:',
    geog: 'Coğrafya:',
    platform: 'Platform:',
    upTo: 'Rakeback üst sınırı',
    bonusL: "Bonus:",
    getDeal: 'Teklifi al',
    rateBy: 'Disiplinlere göre değerlendirmeler',
    verif: 'Tüm teklifler PDH tarafından dahili olarak doğrulanır. Adil iş birliği koşulları ve günün her saati erişilebilen birinci sınıf müşteri desteği garanti ediyoruz.',
    readyJoin: 'Sorularınız mı var? Kulübe katılmaya hazır mısınız?',
    weAreHere: 'Tüm teklifler ücretsiz sunulur. Kulüp üyeliği KYC gerektirmez (belge göndermeye gerek yok).',
    weAreHereNoKyc: `Ek avantajlarınızı öğrenin ve kayıt bağlantınızı alın.`,
    weAreHere2: 'Bir PDH yöneticisine yazın — 7/24 çevrimiçiyiz.',
    tgContact: 'Telegram’dan yazın',
    discordContact: 'Discord’a katıl',
  },
  he: {
    club: 'מועדון:',
    union: 'איגוד:',
    geog: 'גאוגרפיה:',
    platform: 'פלטפורמה:',
    upTo: 'רייקבק עד',
    bonusL: "בונוס:",
    getDeal: 'קבלת העסקה',
    rateBy: 'דירוגים לפי סוג משחק',
    verif: 'כל ההצעות עוברות אימות פנימי של PDH. אנו מבטיחים תנאי שיתוף פעולה הוגנים ותמיכת לקוחות ברמה הגבוהה ביותר הזמינה מסביב לשעון.',
    readyJoin: 'יש שאלות? מוכנים להצטרף למועדון?',
    weAreHere: 'כל העסקאות ניתנות בחינם. החברות במועדונים היא ללא KYC (אין צורך לשלוח מסמכים).',
    weAreHereNoKyc: `גלו את ההטבות הנוספות שלכם וקבלו את קישור ההרשמה שלכם.`,
    weAreHere2: 'כתבו למנהל PDH — אנחנו מקוונים 24/7.',
    tgContact: 'כתבו ב-Telegram',
    discordContact: 'הצטרפו ל-Discord',
  },
  ar: {
    club: 'النادي:',
    union: 'الاتحاد:',
    geog: 'الجغرافيا:',
    platform: 'المنصة:',
    upTo: 'رايك باك حتى',
    bonusL: "بونص:",
    getDeal: 'احصل على العرض',
    rateBy: 'تقييمات حسب نوع اللعبة',
    verif: 'تخضع جميع العروض لتحقق داخلي من قبل PDH. نضمن شروط تعاون عادلة ودعم عملاء من الدرجة الأولى متاح على مدار الساعة.',
    readyJoin: 'هل لديك أسئلة؟ هل أنت مستعد للانضمام إلى النادي؟',
    weAreHere: 'جميع العروض مقدمة مجانًا. عضوية النادي بدون KYC (لا حاجة لإرسال مستندات).',
    weAreHereNoKyc: `تعرّف على مزاياك الإضافية واحصل على رابط التسجيل الخاص بك.`,
    weAreHere2: 'راسل مدير PDH — نحن متصلون على مدار الساعة طوال أيام الأسبوع.',
    tgContact: 'راسلنا على Telegram',
    discordContact: 'انضم إلى Discord',
  },
  id: {
    club: 'Klub:',
    union: 'Union:',
    geog: 'Geografi:',
    platform: 'Platform:',
    upTo: 'Rakeback hingga',
    bonusL: "Bonus:",
    getDeal: 'Dapatkan penawaran',
    rateBy: 'Peringkat berdasarkan jenis permainan',
    verif: 'Semua penawaran menjalani verifikasi internal oleh PDH. Kami menjamin syarat kerja sama yang adil dan dukungan pelanggan kelas atas yang tersedia sepanjang waktu.',
    readyJoin: 'Ada pertanyaan? Siap bergabung dengan klub?',
    weAreHere: 'Semua penawaran diberikan secara gratis. Keanggotaan klub bebas KYC (tidak perlu mengirim dokumen).',
    weAreHereNoKyc: `Pelajari keuntungan tambahan Anda dan dapatkan tautan pendaftaran Anda.`,
    weAreHere2: 'Hubungi manajer PDH — kami online 24/7.',
    tgContact: 'Kirim pesan di Telegram',
    discordContact: 'Gabung Discord',
  },
  vi: {
    club: 'Câu lạc bộ:',
    union: 'Liên minh:',
    geog: 'Khu vực:',
    platform: 'Nền tảng:',
    upTo: 'Rakeback lên đến',
    bonusL: "Tiền thưởng:",
    getDeal: 'Nhận ưu đãi',
    rateBy: 'Xếp hạng theo loại game',
    verif: 'Tất cả ưu đãi đều trải qua quá trình xác minh nội bộ bởi PDH. Chúng tôi đảm bảo điều khoản hợp tác công bằng và hỗ trợ khách hàng hạng nhất sẵn sàng suốt ngày đêm.',
    readyJoin: 'Có câu hỏi? Sẵn sàng tham gia câu lạc bộ?',
    weAreHere: 'Tất cả ưu đãi đều được cung cấp miễn phí. Thành viên câu lạc bộ không cần KYC (không cần gửi tài liệu).',
    weAreHereNoKyc: `Tìm hiểu về các quyền lợi bổ sung của bạn và nhận liên kết đăng ký.`,
    weAreHere2: 'Nhắn tin cho quản lý PDH — chúng tôi trực tuyến 24/7.',
    tgContact: 'Nhắn tin trên Telegram',
    discordContact: 'Tham gia Discord',
  },
  fil: {
    club: 'Club:',
    union: 'Union:',
    geog: 'Heograpiya:',
    platform: 'Platform:',
    upTo: 'Rakeback hanggang',
    bonusL: "Bonus:",
    getDeal: 'Kunin ang deal',
    rateBy: 'Mga rating ayon sa uri ng laro',
    verif: 'Ang lahat ng alok ay sumasailalim sa internal na beripikasyon ng PDH. Ginagarantiya namin ang patas na mga tuntunin ng kooperasyon at top-class na suporta sa customer na available buong araw.',
    readyJoin: 'May tanong? Handa nang sumali sa club?',
    weAreHere: 'Lahat ng deal ay ibinibigay nang libre. Ang membership sa club ay walang KYC (hindi kailangang magpadala ng mga dokumento).',
    weAreHereNoKyc: `Alamin ang iyong mga karagdagang benepisyo at kunin ang iyong link sa pagrerehistro.`,
    weAreHere2: 'Mag-message sa isang PDH manager — online kami 24/7.',
    tgContact: 'Mag-message sa Telegram',
    discordContact: 'Sumali sa Discord',
  },
  th: {
    club: 'คลับ:',
    union: 'ยูเนียน:',
    geog: 'ภูมิภาค:',
    platform: 'แพลตฟอร์ม:',
    upTo: 'เรคแบ็กสูงสุด',
    bonusL: "โบนัส:",
    getDeal: 'รับดีล',
    rateBy: 'คะแนนตามประเภทเกม',
    verif: 'ทุกข้อเสนอผ่านการตรวจสอบภายในโดย PDH เรารับประกันเงื่อนไขความร่วมมือที่เป็นธรรมและการสนับสนุนลูกค้าระดับสูงสุดตลอด 24 ชั่วโมง',
    readyJoin: 'มีคำถามไหม? พร้อมเข้าร่วมคลับหรือยัง?',
    weAreHere: 'ทุกดีลให้บริการฟรี การเป็นสมาชิกคลับไม่ต้องทำ KYC (ไม่ต้องส่งเอกสาร)',
    weAreHereNoKyc: 'เรียนรู้เกี่ยวกับสิทธิประโยชน์เพิ่มเติมของคุณและรับลิงก์สมัคร',
    weAreHere2: 'ทักหาผู้จัดการ PDH — เราออนไลน์ตลอด 24/7',
    tgContact: 'ส่งข้อความทาง Telegram',
    discordContact: 'เข้าร่วม Discord',
  },
};

export interface Deal {
  slug: string;
  name: Record<string, string>;
  description: Record<string, string>;
  club?: string;
  app: string;
  union: string;
  geo: string | Record<string, string>;
  format: string;
  type: string;
  rakeback: string;
  bonus?: string | Record<string, string>;
  logo: string;
  featured: boolean;
  badges?: string[];
  ratings: {
    mtt: number;
    cash: number;
    plo: number;
    nlh?: number;
    ofc?: number;
  };
}


export const getLogoUrl = (logo: string): string => {
  return logoMap[logo] || '/image.webp';
};

/**
 * Resolve a deal collection entry's localized fields for a language,
 * falling back to the source language (ru) when a translation is missing.
 * Pairs with the "source + generated i18n" content model.
 */
export function localizeDeal(data: any, lang: string) {
  const t = (data.i18n && data.i18n[lang]) || {};
  return {
    name: t.name ?? data.name,
    description: t.description ?? data.description,
    geo: t.geo ?? data.geo,
    bonus: t.bonus ?? data.bonus ?? '',
    intro: t.intro ?? data.intro,
    body: t.body ?? data.body,
  };
}

/** Resolve a guide entry's localized fields for a language (i18n -> ru fallback). */
export function localizeGuide(data: any, lang: string) {
  const t = (data.i18n && data.i18n[lang]) || {};
  return {
    title: t.title ?? data.title,
    description: t.description ?? data.description,
    body: t.body ?? data.body,
  };
}

/** Resolve a static page entry's localized fields for a language (i18n -> ru fallback). */
export function localizePage(data: any, lang: string) {
  const t = (data.i18n && data.i18n[lang]) || {};
  return {
    title: t.title ?? data.title,
    description: t.description ?? data.description ?? "",
    body: t.body ?? data.body,
  };
}
